# Generated by Django 5.1.2 on 2024-10-29 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('clave_cliente', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Zonas_disponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficinas', models.BooleanField(default=True)),
                ('salas_de_reuniones', models.BooleanField(default=True)),
                ('escritorios', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('numero_personas', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('zonas_disponibles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zonas_disponibles')),
            ],
        ),
        migrations.CreateModel(
            name='Cancelar_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feccha_cancelacion', models.DateTimeField()),
                ('motivo', models.CharField(max_length=100)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
    ]
